<template>
  <div class="doc-container">
    <div class="doc-sidebar">
      <div class="sidebar-header">
        <el-icon><Reading /></el-icon> <span>CONTENTS</span>
      </div>
      <ul class="toc-list">
        <li 
          v-for="(item, index) in toc" 
          :key="index"
          :class="{ active: activeSection === item.id, 'sub-item': item.level > 1 }"
          @click="scrollTo(item.id)"
        >
          {{ item.text }}
        </li>
      </ul>
    </div>

    <div class="doc-content markdown-body" ref="contentRef" @scroll="handleScroll">
      <div v-html="parsedMarkdown"></div>
      
      <div class="doc-footer">
        Generated by Hometown System Generator &copy; 2025
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, nextTick } from 'vue'
import { Reading } from '@element-plus/icons-vue'
import { marked } from 'marked'
import hljs from 'highlight.js'
import 'highlight.js/styles/github-dark-dimmed.css'

// --- 📝 项目核心文档 (Markdown) ---
// ✨ 关键修复：所有的代码块符号 ``` 都已转义为 \`\`\`，防止 Vue 编译器报错
const markdownContent = `
# 衢州地区信息管理系统 (Hometown Management System)

> **版本**: v1.0.5
> **开发者**: mjc (23H034160336)  
> **状态**: 🟢 已部署 (Stable)

---

## 1. 项目概述 (Overview)

本项目是一个致力于**弘扬衢州文化、推广地方特色**的全栈信息管理平台。系统集成了**文化遗产展示、特产推广、旅游景点导航**以及**后台数据可视化管理**等功能。

**v1.0.5 核心升级**：重点增强了系统的**安全性**与**审计能力**，全面实装了**IP属地监控系统**，并优化了底层数据库交互逻辑。

---

## 2. 技术栈 (Tech Stack)

### 🛠️ 后端 (Backend)
-   **核心框架**: Spring Boot 2.7.x
-   **ORM**: MyBatis / MyBatis-Plus
-   **数据库**: MySQL 8.0
-   **IP解析**: **Ip2Region (离线 IP 库，毫秒级查询)** [NEW]
-   **缓存**: Redis (用于会话管理与热点数据缓存)
-   **安全**: JWT (JSON Web Token) 鉴权
-   **监控**: OSHI (System Hardware Information) 
-   **工具**: Swagger/Knife4j, Lombok, FastJSON
-   **云服务**: 阿里云 OSS (对象存储)

### 💻 前端 (Frontend)
-   **框架**: Vue 3 (Composition API)
-   **构建**: Vite 4.x
-   **UI 组件库**: Element Plus (表格自适应优化)
-   **图表**: ECharts 5.x (数据大屏)
-   **地图**: 百度地图 JavaScript API GL
-   **HTTP**: Axios

---

## 3. 系统架构 (Architecture)

\`\`\`mermaid
graph TD
    User[用户/管理员] -->|登录/操作| Gateway[Nginx / 网关]
    Gateway --> Server(Spring Boot 后端)
    
    subgraph "核心服务层"
    Server -->|解析IP| Ip2Region[IP 属地库]
    Server -->|读写| DB[(MySQL 数据库)]
    Server -->|缓存| Cache[(Redis)]
    Server -->|监控| Hardware[OSHI 硬件监控]
    end
    
    subgraph "安全层"
    Git[Git 仓库] --x|忽略| Sensitive[.yml 配置文件]
    end
\`\`\`

---

## 4. 核心功能模块 (Modules)

### 👮 安全与审计 (Security & Audit) **[NEW]**
-   **IP 属地监控**: 自动获取用户客户端 IP，离线解析出“省份·城市”（如：浙江·宁波），并记录在数据库中。
-   **登录追踪**: 管理员和用户登录/注册时，自动更新最后登录 IP 和地点。
-   **敏感信息保护**: 配置 Git 忽略规则，防止阿里云 AK/SK 泄露。

### 🗺️ 分布地图 (Attraction Map)
-   **全域导览**: 集成百度地图 GL，直观展示衢州所有景点的地理分布。
-   **智能定位**: 支持数据库经纬度直接打点，同时也支持基于地址的自动解析兜底方案。
-   **沉浸体验**: 3D 倾斜视角 + 飞行跳转动画 (FlyTo)。

### 🖥️ 服务监控 (Server Monitor)
-   **实时仪表盘**: 实时监控服务器的 CPU 使用率、内存占用率。
-   **环境信息**: 展示服务器操作系统、IP 地址、Java 版本、项目路径等。

### 🏛️ 文化与特产 (Culture & Food)
-   **非遗展示**: 收录衢州各类非物质文化遗产，支持富文本展示。
-   **特产美食**: 三头一掌、烤饼等特色美食介绍。

---

## 5. 核心代码片段 (Code Snippets)

### 🌍 1. IP 属地智能解析 (Java) **[NEW]**
\`\`\`java
/**
 * 根据 IP 解析城市信息
 * 输入: 110.19.106.1 -> 输出: 浙江·宁波
 */
public static String getCityInfo(String ip) {
    try {
        // 1. 查询 IP 库 (格式: 国家|区域|省份|城市|ISP)
        String region = searcher.search(ip);
        String[] parts = region.split("\\\\|"); // 转义管道符
        
        // 2. 提取并简化
        String province = parts[2];
        String city = parts[3];
        
        // 3. 智能拼接
        return simplifyArea(province) + "·" + simplifyArea(city);
    } catch (Exception e) {
        return "未知";
    }
}
\`\`\`

### 🔧 2. MyBatis 动态更新修复 (XML) **[NEW]**
\`\`\`xml
<update id="updateIpAndCity">
    update user
    <set>
        <if test="ip != null">ip = #{ip},</if>
        <if test="city != null">city = #{city},</if>
        update_time = now(), </set>
    where id = #{id}
</update>
\`\`\`

### 📡 3. OSHI 获取系统信息 (Java)
\`\`\`java
public void copyTo() throws Exception {
    SystemInfo si = new SystemInfo();
    HardwareAbstractionLayer hal = si.getHardware();
    setCpuInfo(hal.getProcessor());
    setMemInfo(hal.getMemory());
    setSysInfo();
}
\`\`\`

### 🗺️ 4. 百度地图智能打点 (JavaScript)
\`\`\`javascript
const addCreativeMarker = (item) => {
  // 🟢 优先使用数据库经纬度 (高性能)
  if (item.longitude && item.latitude) {
    const point = new BMapGL.Point(item.longitude, item.latitude)
    createMarkerLogic(point, item)
  } else {
    // 🟡 兜底：使用地址解析
    const myGeo = new BMapGL.Geocoder()
    myGeo.getPoint('衢州市 ' + item.name, (p) => {
      if (p) createMarkerLogic(p, item)
    }, '衢州市')
  }
}
\`\`\`

---

## 6. 部署指南 (Deployment)

### 启动步骤
1.  **数据库**: 导入 \`init.sql\`。
2.  **后端**: 修改 \`application.yml\` (注意不要提交到 Git)，运行 \`HometownApplication.java\`。
3.  **前端**: 
    \`\`\`bash
    cd vue_hometown_management
    npm install
    npm run dev
    \`\`\`

---

## 7. 更新日志 (Changelog)

-   **v1.0.5 (2025-12-28)**: 
    -   ✨ **[Feature]** 全面实装 **IP 属地监控** 功能，支持用户/管理员登录时自动记录所在城市。
    -   🐛 **[Bugfix]** 修复了 MyBatis \`update\` 语句中因多余逗号导致的 \`SQLSyntaxErrorException\`。
    -   🔒 **[Security]** 修复了 Git 历史记录中的 **阿里云 AK 泄露** 问题，重构了 \`.gitignore\` 规则。
    -   💄 **[UI]** 优化了后台管理表格，IP 归属地列支持自适应宽度。

-   **v1.0.4 (2025-12-19)**:
    -   ✨ **[Feature]** 新增 **“分布地图”** 模块，支持全屏 3D 地图导览。
    -   ✨ **[Feature]** 新增 **“服务监控”** 模块，基于 OSHI 实时展示服务器状态。

-   **v1.0.0 (2025-09-15)**: 
    -   🎉 项目初始化，完成基础 CRUD 功能。

---

> **Copyright**: 2025 衢州地区信息管理系统 Team. All Rights Reserved.
`

// --- 逻辑处理 ---
const contentRef = ref(null)
const activeSection = ref('')

// 配置 Marked
marked.setOptions({
  renderer: new marked.Renderer(),
  highlight: function(code, lang) {
    const language = hljs.getLanguage(lang) ? lang : 'plaintext';
    return hljs.highlight(code, { language }).value;
  },
  langPrefix: 'hljs language-',
  pedantic: false,
  gfm: true,
  breaks: false,
  sanitize: false,
  smartLists: true,
  smartypants: false,
  xhtml: false
});

const parsedMarkdown = computed(() => marked(markdownContent))

// 生成目录 (TOC)
const toc = computed(() => {
  const reg = /^#+\s+(.*)$/gm
  const matches = markdownContent.match(reg) || []
  return matches.map((item, index) => {
    const level = item.match(/^#+/)[0].length
    const text = item.replace(/^#+\s+/, '')
    const id = `heading-${index}`
    return { level, text, id }
  })
})

// 为生成的 HTML 添加 ID 以便跳转
onMounted(async () => {
  await nextTick()
  const headers = contentRef.value.querySelectorAll('h1, h2, h3')
  headers.forEach((header, index) => {
    header.id = `heading-${index}`
  })
})

// 滚动跳转
const scrollTo = (id) => {
  const el = document.getElementById(id)
  if (el) {
    el.scrollIntoView({ behavior: 'smooth' })
    activeSection.value = id
  }
}

const handleScroll = () => {
  // scroll logic
}
</script>

<style scoped>
/* 样式保持不变 */
.doc-container {
  display: flex;
  height: 100%;
  background-color: #ffffff;
  font-family: 'Segoe UI', sans-serif;
  overflow: hidden; 
}

.doc-sidebar {
  width: 280px;
  background-color: #f8f9fa;
  border-right: 1px solid #e9ecef;
  padding: 30px 20px;
  overflow-y: auto;
  flex-shrink: 0;
}

.sidebar-header {
  font-size: 14px;
  font-weight: 800;
  color: #adb5bd;
  margin-bottom: 20px;
  display: flex;
  align-items: center;
  gap: 8px;
  letter-spacing: 1px;
}

.toc-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.toc-list li {
  padding: 8px 12px;
  font-size: 14px;
  color: #495057;
  cursor: pointer;
  border-radius: 6px;
  transition: all 0.2s;
  margin-bottom: 4px;
  border-left: 3px solid transparent;
}

.toc-list li:hover {
  background-color: #e9ecef;
  color: #212529;
}

.toc-list li.active {
  background-color: #e7f5ff;
  color: #1a5e38;
  border-left-color: #1a5e38;
  font-weight: 600;
}

.toc-list li.sub-item {
  padding-left: 25px;
  font-size: 13px;
  color: #868e96;
}

.doc-content {
  flex: 1;
  padding: 40px 60px;
  overflow-y: auto;
  scroll-behavior: smooth;
  background-color: #fff;
}

:deep(.markdown-body) {
  color: #24292f;
  line-height: 1.6;
}

:deep(h1) {
  font-size: 2.5em;
  padding-bottom: 0.3em;
  border-bottom: 1px solid #eaecef;
  margin-bottom: 24px;
  color: #1a5e38;
}

:deep(h2) {
  font-size: 1.75em;
  padding-bottom: 0.3em;
  border-bottom: 1px solid #eaecef;
  margin-top: 36px;
  margin-bottom: 20px;
}

:deep(h3) {
  font-size: 1.4em;
  margin-top: 24px;
  margin-bottom: 16px;
}

:deep(p) {
  margin-bottom: 16px;
}

:deep(blockquote) {
  padding: 0 1em;
  color: #6a737d;
  border-left: 0.25em solid #dfe2e5;
  background-color: #f6f8fa;
  padding: 16px;
  margin: 0 0 16px 0;
  border-radius: 4px;
}

:deep(pre) {
  background-color: #2d333b; 
  padding: 16px;
  border-radius: 8px;
  overflow: auto;
  margin-bottom: 20px;
}

:deep(code) {
  font-family: 'Consolas', 'Monaco', monospace;
}

:deep(pre code) {
  color: #adbac7;
  background: transparent;
  padding: 0;
}

:deep(:not(pre) > code) {
  padding: 0.2em 0.4em;
  margin: 0;
  font-size: 85%;
  background-color: rgba(175, 184, 193, 0.2);
  border-radius: 6px;
}

:deep(ul) {
  padding-left: 2em;
  margin-bottom: 16px;
}

:deep(li) {
  margin-bottom: 4px;
}

.doc-footer {
  margin-top: 60px;
  padding-top: 20px;
  border-top: 1px solid #eee;
  text-align: center;
  color: #999;
  font-size: 12px;
}

.doc-content::-webkit-scrollbar,
.doc-sidebar::-webkit-scrollbar {
  width: 6px;
}
.doc-content::-webkit-scrollbar-thumb,
.doc-sidebar::-webkit-scrollbar-thumb {
  background-color: #ddd;
  border-radius: 3px;
}
</style>